[build]
dist = "dist"
release = true
target = "curiosity/index.html"

[serve]
address = "0.0.0.0"
no_autoreload = false
open = false
port = 8080



# [[hooks]]
# stage = "build"
# command = "sh"
# command_arguments = ["-c", "npx tailwindcss-cli build static/tailwind.css -o $TRUNK_STAGING_DIR/tailwind.css"]